### ISSUE TITLE
fixed the folder structure properly 

### ISSUE THREAD

**Issue by PMArtz92** [UCSC-LK/CV-APP#12]
in current repo folder structure is bit messy need to re-arrange the structure.

**Comment by BhaveshSGupta** [comment]
I can take this one, how you want your folder structure to be

**Comment by PMArtz92** [comment]
Hi @BhaveshSGupta @chamathsilva is looking on this matter can you check on the other issue, #15 this one?

**Comment by BhaveshSGupta** [comment]
@PMArtz92 i think #15 is already closed

**Comment by PMArtz92** [comment]
@BhaveshSGupta we will tell when there is new issues :) thank you for your effort.
