### ISSUE TITLE
Input type of Telephone number should be `tel`

### ISSUE THREAD

**Issue by agentmilindu** [UCSC-LK/CV-APP#22]
Current Input type of Telephone number is  `number`. It does not allows to enter telephone numbers in '+94xxxxxxxxx' fashion. And using input type `tel` for telephone numbers is the correct semantic.

**Comment by MilindaLaknath** [comment]
Making it `tel` is not good. It doesn't support every browser.
The tel type is currently supported only in Safari 8.
http://www.w3schools.com/html/html_form_input_types.asp

**Comment by MilindaLaknath** [comment]
Make it as `text` and give format.

**Comment by agentmilindu** [comment]
Do not believe w3schools! See the compatibility on html5test.com

[https://html5test.com/compare/feature/form.tel.element.html](https://html5test.com/compare/feature/form.tel.element.html)

However, 

> New input types that are not supported by older web browsers will behave as `<input type="text">`.

No worries if the browser does not support.

**Comment by MilindaLaknath** [comment]
I checked. It's working Firefox, Chrome and Opera.
Thank you.
