### ISSUE TITLE
Should show the user's name

### ISSUE THREAD

**Issue by agentmilindu** [UCSC-LK/CV-APP#35]
![image](https://cloud.githubusercontent.com/assets/1391468/19249001/c28443bc-8f50-11e6-9795-60c4ae473378.png)

We have to show the user's name here. Not John Doe!

**Comment by wiewioraseb** [comment]
Is this issue taken? I would like to work on it.

**Comment by dhruvdutt** [comment]
I would like to work on this too.

**Comment by wiewioraseb** [comment]
@dhruvdutt Sorry, I'm already working on it.

**Comment by wiewioraseb** [comment]
@agentmilindu I can't login or signup. I get "Cannot POST /userlogin" or "Cannot POST /userregister". I have my server, client and mongodb running. Would you be so kind and tell me step by step what should I do to be able to login? Or maybe you could update the README.md file.

**Comment by agentmilindu** [comment]
@PMartz92

**Comment by redice44** [comment]
You have to build the server as well. Since you're working on this already, I'll make a quick PR updating the readme, so people can get this project up and running 🙂👍

**Comment by PMArtz92** [comment]
this issue is fixed.
